FROM docker.io/library/eclipse-temurin:8-jre-jammy as builder

RUN apt-get update && apt-get install -y  unzip && rm -rf /var/lib/apt/lists/*

COPY payara5.zip /tmp/payara5.zip

RUN mkdir -p /opt && \
    unzip /tmp/payara5.zip -d /opt && \
    rm /tmp/payara5.zip

FROM docker.io/library/eclipse-temurin:8-jre-jammy as payara

ARG TIMEZONE=America/Lima
ARG PAYARA_DIR=/opt/payara5 

RUN apt-get update && \
    ln -snf /usr/share/zoneinfo/$TIMEZONE /etc/localtime &&  echo $TIMEZONE > /etc/timezone && \
    echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | debconf-set-selections && \
    apt-get install -y --no-install-recommends ttf-mscorefonts-installer fontconfig && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /tmp /glassfish/tmp /glassfish/tmppcm /opt 

COPY --from=builder /opt/payara5 /opt/payara5

CMD ["/opt/payara5/bin/asadmin", "start-domain", "--verbose", "domain1"]